{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.sensorsdata.asmbook.plugin",
    "module": "myPlugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "bgjgyuclxneoxfzkl6iwavbmyu"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "myPlugin-1.0.0.jar",
          "url": "myPlugin-1.0.0.jar",
          "size": 2212,
          "sha512": "3e381678323aec57eebb959c8483c3e03628b4f66dede1c1fbc1f94395f2830f0267d2f2450a80df1959d28e1596e48db2f861fd825dd42395fbf6f953a99285",
          "sha256": "0e39e5ec9aa62bb3915342e9b628a873c96531edf1f4d8ea2aff7065a1e3e20c",
          "sha1": "f9d4d7414ffb16bd48811352a39967f10777f708",
          "md5": "928165f7f109895fae1f10ac42f18c19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myPlugin-1.0.0.jar",
          "url": "myPlugin-1.0.0.jar",
          "size": 2212,
          "sha512": "3e381678323aec57eebb959c8483c3e03628b4f66dede1c1fbc1f94395f2830f0267d2f2450a80df1959d28e1596e48db2f861fd825dd42395fbf6f953a99285",
          "sha256": "0e39e5ec9aa62bb3915342e9b628a873c96531edf1f4d8ea2aff7065a1e3e20c",
          "sha1": "f9d4d7414ffb16bd48811352a39967f10777f708",
          "md5": "928165f7f109895fae1f10ac42f18c19"
        }
      ]
    }
  ]
}
